### ISSUE TITLE
targetUsers

### ISSUE THREAD

**Issue by phaitonican** [p0o/steem-bot#22]
Hello again,
I followed your code and change targetUsers with my DB function. if I change 'targetUsers' with another value, it likes the post. otherwise nothing happens. even though targetUsers has a value... You maybe got an idea? I just read you can't connect to MongoDB synchronously, so there is no possible way?
```
function cb(err, results) {
  if(typeof results !== 'undefined') {
    targetUsers = results;
    console.log(targetUsers); //works!
  }
}

function getMembers(cb) {

  const results = [];

  mongodb.MongoClient.connect(uri, function(err, client) {

    if(err) {
      return cb(err);
    }

    let db = client.db('members');

    let members = db.collection('members');

    members.find({}).forEach(function(row) {
      results.push(row.member);
    },

    function(err) {

      cb(err, results);

    });
    client.close();
  });
}

bot.onPost(targetUsers, handlePost);
bot.onComment(handleComment);

function handlePost(data, responder) {
  responder.upvote();
}
function handleComment(data, responder) {
  getMembers(cb);
}
```

**Comment by p0o** [comment]
You should omit the first parameter for the bot in order to control the targetUsers yourself. If you send the target user like this `bot.onPost(targetUsers, handlePost);` there is no way to change it later because the listener is already set (refer again to my code at #21 )

Of course most of your data is retrieved asynchronously, but you can perform regular asynchronous data update in the background and have a function to return the latest changes synchronously. Something like:

```javascript
setInterval(() => { getMembers(cb) }, 3000 ); 
```

**Comment by phaitonican** [comment]
Oh I got now what you mean. Also set it up like that.
Changing targetUsers on the fly and without omitting the first parameter. Seems like he is liking everyone. hmmm

```
bot.onPost(handlePost);

setInterval(() => { getMembers(cb); console.log('doing it') }, 3000 );

function handlePost(data, responder) {
  console.log(targetUsers); //shows DB users
  responder.upvote();
}
```

**Comment by p0o** [comment]
It's liking everyone because you don't exit the function when it doesn't match your targetUsers. I put the code in #21 for you to do that, this line inside the function will do the trick:

```javascript
 // exit if author is not in targetUsers
  if(!targetUsers.includes(data.author)) return;
```

If `data.author` is not one of the members of your `targetUsers` it will return the function and stop the execution of `responder.upvote()`

**Comment by phaitonican** [comment]
oh yes, you are totally right. i made it work like that. thank you !
